name = "telegram-notification-mcp"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
new_sqlite_classes = ["TelegramMCP"]
tag = "v1"

[[durable_objects.bindings]]
class_name = "TelegramMCP"
name = "MCP_OBJECT"

[observability]
enabled = true